### ISSUE TITLE
values for top, left backwards

### ISSUE THREAD

**Issue by jove4015** [brandonaaron/jquery-overlaps#1]
Your code works great for me, thank you!  But I needed to make one tweak to checkOverlap:

```
var x1 = dims1[1], y1 = dims1[0],
    w1 = dims1[2], h1 = dims1[3],
    x2 = dims2[1], y2 = dims2[0],
    w2 = dims2[2], h2 = dims2[3];
```

because 0 is top and 1 is left...  

Before that it was totally random if it would work or not, unless the elements in question were perfectly square.

**Comment by brandonaaron** [comment]
Whoops! This is now fixed. Thanks. :)
