### ISSUE TITLE
value of overlapping

### ISSUE THREAD

**Issue by stefanocudini** [brandonaaron/jquery-overlaps#2]
hi
I'm stefano

I was im programming a simple chess game in jquery
and I used your plugin to make event that when you drag a pawn in the chessboard is highlighted, this happens by filtering the bottom square of the board in accordance with the overlap condition

but there is one problem

I would need to be able to have a value of overlap, that is, find out which square the pawn is covered  under most of other

you think that you can implement this piece to your plugin? do you already thought it?
I would like to help you in this if I can, but I do not know where to start

thanks
stefano

**Comment by amundo** [comment]
+1 on this. I'm trying to implement a list of which elements are touching a given element (for grouping purposes). 

I'm gonna see if I can figure out if I can make a fork work (though I'm sure Brandon could do it better :P ).

Thanks for the cool plugin Brandon.

**Comment by brandonaaron** [comment]
I believe this is a bit out of scope for this plugin. The plugin now returns the matching elements that are overlapping. You could look at their offsets and do the calculation after filtering/matching though.
