### ISSUE TITLE
Way to return a list which elements are overlapped rather than boolean

### ISSUE THREAD

**Issue by amundo** [brandonaaron/jquery-overlaps#3]
I'm trying to implement a list of which elements are touching a given element (for grouping purposes). 

In the four divs in your `test/test.html`, where `#three` is out on its own and `#one`, `#two`, and `#three` are overlapping, it would be cool to be able to do:

```
$('#two').isOverLappedBy() // not sure that method name would be good...
```

and have that return, not a boolean `true`, but a list  including the elements `#one` and `#four`.

I'll see if I can figure out if I can make a fork work (though I'm sure Brandon could do it better :P ).

(Thanks for the cool plugin Brandon!)

**Comment by brandonaaron** [comment]
I've changed the functionality in 1.2 to support this rather than a boolean. You can always check if the length is 0 to get the boolean behavior.
