### ISSUE TITLE
Incorrectly determining that adjacent elements are overlapping

### ISSUE THREAD

**Issue by joeyb9686** [brandonaaron/jquery-overlaps#4]
Hi,

The current release incorrectly identifies adjacent elements as overlapping:

Using jquery draggables with 'snap' enabled (to place elements directly next to each other), I placed two square elements next to each other with the following dimensions (dumped from getDims()):

el1:     top: 210, left: 367, w: 90, h: 90
el2:     top: 210, left: 457, w: 90, h: 90

Now, if(pixel[0] is a 367, the right-most (90th, or pixel [89]) of el1 are actually at 456, not 457;

thusly, we need to change  line 88:
from       return !(y2 + h2 < y1 || y1 + h1 < y2 || x2 + w2 < x1 || x1 + w1 < x2);

to           return !(y2 + h2 <= y1 || y1 + h1 <= y2 || x2 + w2 <= x1 || x1 + w1 <= x2);

Regards,

Joe

P.S. Otherwise, a cracking piece of code ;)

**Comment by brandonaaron** [comment]
Fixed.
