### ISSUE TITLE
Finding overlapping elements, but not returning them

### ISSUE THREAD

**Issue by 13protons** [brandonaaron/jquery-overlaps#6]
I'm trying out your plugin, and I looks like only the first element in the overlaps collection is being returned (see screenshot of my browser console). 

I have a 15x30 grid with divs, and one larger "window". Overlaps correctly shows that 280 of the 450 divs overlap that larger window, but all of them come back "undefined".

![Screen Shot 2013-03-15 at 5 28 55 PM](https://f.cloud.github.com/assets/1456258/265634/62b6c6b0-8db7-11e2-87e0-a4b8a980863f.png)

**Comment by brandonaaron** [comment]
I believe this is now fixed in 1.2.3.
