### ISSUE TITLE
Returning incorrect element.

### ISSUE THREAD

**Issue by McKatsu** [brandonaaron/jquery-overlaps#7]
Maybe I'm just using it wrong, but I believe I have found an issue on line 38. I believe the line should be

``` javascript
stack.push(collection1[index1]);
```

When I run the following code I always get the first tbody with the code as is, but when I change it as shown above I get the correct element.

``` javascript
$('tbody').overlaps(ui.helper)
```

**Comment by brandonaaron** [comment]
I believe this is now fixed in 1.2.3.
